In [ ]:
import pandas as pd

In [ ]:
#1차원 데이터 -> series
#2차원 데이터 -> data frame

In [ ]:
data = [1,2,3,4,5]
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#index 매개변수를 사용해서 인덱스 조정 가능
pd.Series(data, index=["a","b","c","d","e"])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
name = ["kim", "seo", "park", "lee"]
birth = [12, 13, 14, 15]

df = pd.DataFrame(name, index=["a","b","c","d"], columns=["name"])

In [ ]:
df

name
a   kim
b   seo
c  park
d   lee

In [ ]:
df["name"]

a     kim
b     seo
c    park
d     lee
Name: name, dtype: object

In [ ]:
df.loc["b"]

name    seo
Name: b, dtype: object

In [ ]:
df.loc["b"]

name    seo
Name: b, dtype: object

In [ ]:
df.shape

(4, 1)

In [ ]:
df.empty #데이터프레임 내에 공백(비어있는 값)이 있는지?

False

In [ ]:
df.head(2)

name
a  kim
b  seo

In [ ]:
df.tail(2)

name
c  park
d   lee

In [ ]:
data_a = [[1.4, None],
        [4, None],
        [1.4, 7],
        [1.4, 8]]

print(data_a)

[[1.4, None], [4, None], [1.4, 7], [1.4, 8]]


In [ ]:
df2 = pd.DataFrame(data_a, index=["a","b","c","d"], columns=["one","two"])

In [ ]:
df3 = pd.DataFrame(data_a, ["a","b","c","d"], ["one","two"])

In [ ]:
df2

one  two
a  1.4  NaN
b  4.0  NaN
c  1.4  7.0
d  1.4  8.0

one    1.69
two    0.50
dtype: float64

In [ ]:
df2.var(axis=1) # axis = 0 (열을 기준으로)

a      NaN
b      NaN
c    15.68
d    21.78
dtype: float64

In [ ]:
df2

one  two
a  1.4  NaN
b  4.0  NaN
c  1.4  7.0
d  1.4  8.0

In [ ]:
df2.fillna(0)

one  two
a  1.4  0.0
b  4.0  0.0
c  1.4  7.0
d  1.4  8.0

In [ ]:
df2

one  two
a  1.4  NaN
b  4.0  NaN
c  1.4  7.0
d  1.4  8.0

In [ ]:
df2.count()

one    4
two    2
dtype: int64

In [ ]:
df2.count(axis=1)

a    1
b    1
c    2
d    2
dtype: int64

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
b = (1,2,3,4)
len(b)

4

In [ ]:
print("(4)")

(4)


In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

4

In [ ]:
a = np.array([[1,2,3,4],
              [1,2,3,4]])

print(a)
print(a.ndim)
rint(a.shape)

[[1 2 3 4]
 [1 2 3 4]]
2
(2, 4)


In [ ]:
a = np.array([[[[1,2,3,4],
               [1,2,3,4]],
               [[1,2,3,4],
               [1,2,3,4]]],

              [[[1,2,3,4],
               [1,2,3,4]],
               [[1,2,3,4],
               [1,2,3,4]]]])



print(a)
print(a.ndim)
print(a.shape)

[[[[1 2 3 4]
   [1 2 3 4]]

  [[1 2 3 4]
   [1 2 3 4]]]


 [[[1 2 3 4]
   [1 2 3 4]]

  [[1 2 3 4]
   [1 2 3 4]]]]
4
(2, 2, 2, 4)


In [ ]:
b = np.zeros([3,3,3,3])
print(b)
print(b.ndim)
print(b.shape)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]
4
(3, 3, 3, 3)


In [ ]:
b = np.ones([3,3,3,3])
print(b)
print(b.ndim)
print(b.shape)

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
4
(3, 3, 3, 3)


In [ ]:
np. random.seed(41231232)

a = np.random.randint(1,100, (3,3))
print(a)

[[52 80 80]
 [32 53  7]
 [44  3 50]]


In [ ]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
b = a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
a.shape

(10,)

In [ ]:
a = np.arange(1,11)
print(a.shape)
b = a.reshape(2,5)
print(b.shape)

(10,)
(2, 5)


In [ ]:
a = np.ones([3,3])
print(a)
print("  ")
b = np.ones([3,3])
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
  
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a+b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
b = np.arange(1,5).reshape(2,2)
print(b)

[[1 2]
 [3 4]]


In [ ]:
a+b

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [125]:
import pandas as pd

a = [[], [], [], []]
cnt = 0

for i in range(2,6):
    for j in range(1,10):
        a[cnt].append(i*j)
        #print(a)
    cnt += 1


df= pd.DataFrame(data= a, index=["2단","3단","4단","5단"] , columns=[1,2,3,4,5,6,7,8,9])
df

1   2   3   4   5   6   7   8   9
2단  2   4   6   8  10  12  14  16  18
3단  3   6   9  12  15  18  21  24  27
4단  4   8  12  16  20  24  28  32  36
5단  5  10  15  20  25  30  35  40  45

In [126]:
import numpy as np

In [129]:
def lotto_np():
    lotto = []
    while len(lotto) < 6:
        num = np.random.randint(1,46)
        print(num)
        if num not in lotto:
            lotto.append(num)
    return sorted(lotto)

In [130]:
lotto_np()

7
8
45
33
43
43
43
35


[7, 8, 33, 35, 43, 45]